#!/usr/bin/env node

import { writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const packageRoot = join(__dirname, "..");

interface DeepSeekModelDefinition {
	id: string;
	name: string;
	inputCost: number;
	outputCost: number;
	cacheReadCost: number;
	contextWindow: number;
	maxTokens: number;
}

const DEEPSEEK_THINKING_LEVEL_MAP = {
	minimal: null,
	low: null,
	medium: null,
	high: "high",
	xhigh: "max",
} as const;

const MODELS: DeepSeekModelDefinition[] = [
	{
		id: "deepseek-v4-flash",
		name: "DeepSeek V4 Flash",
		inputCost: 0.14,
		outputCost: 0.28,
		cacheReadCost: 0.0028,
		contextWindow: 1_000_000,
		maxTokens: 384_000,
	},
	{
		id: "deepseek-v4-pro",
		name: "DeepSeek V4 Pro",
		inputCost: 0.435,
		outputCost: 0.87,
		cacheReadCost: 0.003625,
		contextWindow: 1_000_000,
		maxTokens: 384_000,
	},
];

function serializeModel(model: DeepSeekModelDefinition): string {
	return `		"${model.id}": {
			id: "${model.id}",
			name: "${model.name}",
			api: "openai-completions",
			provider: "deepseek",
			baseUrl: "https://api.deepseek.com",
			compat: ${JSON.stringify({ requiresReasoningContentOnAssistantMessages: true, thinkingFormat: "deepseek" })},
			reasoning: true,
			thinkingLevelMap: ${JSON.stringify(DEEPSEEK_THINKING_LEVEL_MAP)},
			input: ["text"],
			cost: {
				input: ${model.inputCost},
				output: ${model.outputCost},
				cacheRead: ${model.cacheReadCost},
				cacheWrite: 0,
			},
			contextWindow: ${model.contextWindow},
			maxTokens: ${model.maxTokens},
		} satisfies Model<"openai-completions">,`;
}

const modelEntries = MODELS.map(serializeModel).join("\n");
const output = `// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "./types.ts";

export const MODELS = {
	"deepseek": {
${modelEntries}
	},
} as const;
`;

const outputPath = join(packageRoot, "src", "models.generated.ts");
writeFileSync(outputPath, output, "utf-8");
console.log(`Generated ${outputPath}`);
